### ISSUE TITLE
Patient Card component does not update when the patient prop changes

### ISSUE THREAD

**Issue by AlexErdei73** [healthintellect/fhir-ui#1]
Description: I realised that the Patient Card component renders correctly the patient data from the patient prop at the first rendering. Whenever the patient prop changes and the component renders again, it keeps the data from the first rendering instead of updating the patient data from the new value of the patient prop.

Probable reason: The useEffect hook, which is responsible for updating the state of the component (currentPatient) runs only at the first rendering, instead of running at each rendering. 

Possible fix: You should remove the second parameter (the empty array) of the useEffect hook in the source code of the component then build it like that.

**Comment by braytonstafford** [comment]
Thank you for the feedback, I have added the useEffect dependencies for the components where dynamic data could be passed into it, v0.6.3 has been published and should resolve this issue.
